[project]
name = "phoneapp"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "dale", email = "dalesikkema@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pyserial>=3.5",
]

[project.scripts]
phoneapp = "phoneapp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
